/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frontEnd;

import backEnd.Equipo;
import backEnd.EquipoDAO;
import backEnd.Jugador;
import backEnd.JugadorDAO;
import backEnd.Utilidades;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author josue
 */
public class VistaJugadoresActualizar extends javax.swing.JFrame {
    private int idJugador;

    public int getIdJugador() {
        return idJugador;
    }

    public void setIdJugador(int idJugador) {
        this.idJugador = idJugador;
    }
    
    
    /**
     * Creates new form VistaPlantilla
     */
    public VistaJugadoresActualizar() {
        initComponents();
        Utilidades.cargarLogo(this, "LOGOEMPRESA.png");
    }
    
    public VistaJugadoresActualizar(int idJugador) {
        initComponents();
        Utilidades.cargarLogo(this, "LOGOEMPRESA.png");
        
        this.setIdJugador(idJugador);
        try {
            JugadorDAO jugadorDAO = new JugadorDAO();
            
            Jugador jugador1 = jugadorDAO.obtenerJugador(idJugador);
            
            txtfIdJugador.setText(String.valueOf(jugador1.getIdJugador()));
            txtfNombres.setText(jugador1.getNombre());
            txtfApellidoPaterno.setText(jugador1.getApellidoPaterno());
            txtfApellidoMaterno.setText(jugador1.getApellidoMaterno());
            txtfNumeroCamiseta.setText(String.valueOf(jugador1.getNumeroCamiseta()));
            txtfPosicion.setText(jugador1.getPosicion());
            txtfPosicion.setText(jugador1.getPosicion());
            txtfFechaNacimiento.setText(jugador1.getFechaNacimiento());
            txtfIdEquipo.setText(String.valueOf(jugador1.getIdEquipo()));
            
            
        } catch (SQLException ex) {
            Logger.getLogger(VistaJugadoresActualizar.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblIdArbitro1 = new javax.swing.JLabel();
        lblNombres1 = new javax.swing.JLabel();
        lblApellidoPaterno1 = new javax.swing.JLabel();
        lblApellidoMaterno1 = new javax.swing.JLabel();
        lblNumeroCamiseta = new javax.swing.JLabel();
        lblPosicion = new javax.swing.JLabel();
        txtfPosicion = new javax.swing.JTextField();
        txtfIdJugador = new javax.swing.JTextField();
        txtfNombres = new javax.swing.JTextField();
        txtfApellidoPaterno = new javax.swing.JTextField();
        txtfApellidoMaterno = new javax.swing.JTextField();
        btnActualizarJugador = new javax.swing.JButton();
        txtfNumeroCamiseta = new javax.swing.JTextField();
        lblFechaNacimiento = new javax.swing.JLabel();
        txtfFechaNacimiento = new javax.swing.JTextField();
        lblIdEquipo = new javax.swing.JLabel();
        txtfIdEquipo = new javax.swing.JTextField();
        btnRegresar2 = new javax.swing.JButton();
        lblLogoEmpresa = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        lblIcono = new javax.swing.JLabel();
        lblFondo = new javax.swing.JLabel();
        lblAside = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ACTUALIZAR ARBITRO");
        setMinimumSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(null);

        lblIdArbitro1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblIdArbitro1.setText("ID JUGADOR");
        getContentPane().add(lblIdArbitro1);
        lblIdArbitro1.setBounds(350, 50, 190, 40);

        lblNombres1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblNombres1.setText("NOMBRES");
        getContentPane().add(lblNombres1);
        lblNombres1.setBounds(350, 120, 190, 40);

        lblApellidoPaterno1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblApellidoPaterno1.setText("APELLIDO  PATERNO");
        getContentPane().add(lblApellidoPaterno1);
        lblApellidoPaterno1.setBounds(350, 180, 250, 40);

        lblApellidoMaterno1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblApellidoMaterno1.setText("APELLIDO  MATERNO");
        getContentPane().add(lblApellidoMaterno1);
        lblApellidoMaterno1.setBounds(350, 250, 250, 40);

        lblNumeroCamiseta.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblNumeroCamiseta.setText("NUMERO CAMISETA");
        getContentPane().add(lblNumeroCamiseta);
        lblNumeroCamiseta.setBounds(350, 320, 250, 40);

        lblPosicion.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblPosicion.setText("POSICION");
        getContentPane().add(lblPosicion);
        lblPosicion.setBounds(350, 400, 250, 40);

        txtfPosicion.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtfPosicion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfPosicionActionPerformed(evt);
            }
        });
        getContentPane().add(txtfPosicion);
        txtfPosicion.setBounds(670, 400, 330, 40);

        txtfIdJugador.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtfIdJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfIdJugadorActionPerformed(evt);
            }
        });
        getContentPane().add(txtfIdJugador);
        txtfIdJugador.setBounds(670, 50, 330, 40);

        txtfNombres.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtfNombres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfNombresActionPerformed(evt);
            }
        });
        getContentPane().add(txtfNombres);
        txtfNombres.setBounds(670, 110, 330, 40);

        txtfApellidoPaterno.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtfApellidoPaterno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfApellidoPaternoActionPerformed(evt);
            }
        });
        getContentPane().add(txtfApellidoPaterno);
        txtfApellidoPaterno.setBounds(670, 180, 330, 40);

        txtfApellidoMaterno.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtfApellidoMaterno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfApellidoMaternoActionPerformed(evt);
            }
        });
        getContentPane().add(txtfApellidoMaterno);
        txtfApellidoMaterno.setBounds(670, 250, 330, 40);

        btnActualizarJugador.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnActualizarJugador.setText("ACTUALIZAR JUGADOR");
        btnActualizarJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarJugadorActionPerformed(evt);
            }
        });
        getContentPane().add(btnActualizarJugador);
        btnActualizarJugador.setBounds(550, 600, 290, 70);

        txtfNumeroCamiseta.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtfNumeroCamiseta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfNumeroCamisetaActionPerformed(evt);
            }
        });
        getContentPane().add(txtfNumeroCamiseta);
        txtfNumeroCamiseta.setBounds(670, 320, 330, 40);

        lblFechaNacimiento.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblFechaNacimiento.setText("FECHA NACIMIENTO");
        getContentPane().add(lblFechaNacimiento);
        lblFechaNacimiento.setBounds(350, 460, 250, 40);

        txtfFechaNacimiento.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtfFechaNacimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfFechaNacimientoActionPerformed(evt);
            }
        });
        getContentPane().add(txtfFechaNacimiento);
        txtfFechaNacimiento.setBounds(670, 460, 330, 40);

        lblIdEquipo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblIdEquipo.setText("ID EQUIPO");
        getContentPane().add(lblIdEquipo);
        lblIdEquipo.setBounds(350, 520, 250, 40);

        txtfIdEquipo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtfIdEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfIdEquipoActionPerformed(evt);
            }
        });
        getContentPane().add(txtfIdEquipo);
        txtfIdEquipo.setBounds(670, 520, 330, 40);

        btnRegresar2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnRegresar2.setText("REGRESAR");
        btnRegresar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresar2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegresar2);
        btnRegresar2.setBounds(30, 600, 190, 70);

        lblLogoEmpresa.setIcon(new javax.swing.ImageIcon("C:\\Imagenes\\LOGOEMPRESA.png")); // NOI18N
        getContentPane().add(lblLogoEmpresa);
        lblLogoEmpresa.setBounds(20, 80, 180, 190);

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("JUGADOR");
        getContentPane().add(lblTitulo);
        lblTitulo.setBounds(0, 320, 250, 80);

        lblIcono.setIcon(new javax.swing.ImageIcon("C:\\Imagenes\\jugadores.png")); // NOI18N
        getContentPane().add(lblIcono);
        lblIcono.setBounds(1000, 170, 340, 380);

        lblFondo.setIcon(new javax.swing.ImageIcon("C:\\Imagenes\\fondo1.png")); // NOI18N
        getContentPane().add(lblFondo);
        lblFondo.setBounds(250, 0, 1030, 720);

        lblAside.setIcon(new javax.swing.ImageIcon("C:\\Imagenes\\FONDOC.jpg")); // NOI18N
        getContentPane().add(lblAside);
        lblAside.setBounds(0, 0, 1290, 730);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtfPosicionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfPosicionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfPosicionActionPerformed

    private void txtfIdJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfIdJugadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfIdJugadorActionPerformed

    private void txtfNombresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfNombresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfNombresActionPerformed

    private void txtfApellidoPaternoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfApellidoPaternoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfApellidoPaternoActionPerformed

    private void txtfApellidoMaternoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfApellidoMaternoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfApellidoMaternoActionPerformed

    private void btnActualizarJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarJugadorActionPerformed
        // TODO add your handling code here:
        String nombre = txtfNombres.getText();
        System.out.println(nombre);
        
        String apellidoPaterno = txtfApellidoPaterno.getText();
        System.out.println(apellidoPaterno);
        
        String apellidoMaterno = txtfApellidoMaterno.getText();
        System.out.println(apellidoMaterno);
        
         int numeroCamiseta = Integer.valueOf(txtfNumeroCamiseta.getText());
         System.out.println(numeroCamiseta);
         
         String posicion = txtfPosicion.getText();
         System.out.println(posicion);
         
         String fechaNacimiento = txtfFechaNacimiento.getText();
         System.out.println(fechaNacimiento);
         
        int idEquipo = Integer.valueOf(txtfIdEquipo.getText());
         System.out.println(idEquipo);
         
        //CONFIRMACION DE CREAR
        int result = JOptionPane.showConfirmDialog(
                new JFrame(),
                "¿ESTAS SEGURO DE ACTUALIZARLO?", 
                "CANCHASGONZALEZ - CONFIRMACION",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE
            );

        if(result == JOptionPane.YES_OPTION){
            System.out.println(1);
            Jugador jugador1 = new Jugador(idEquipo, nombre, apellidoPaterno, apellidoMaterno, numeroCamiseta, posicion, fechaNacimiento);
            
            System.out.println(jugador1);
          
            int id;
            try {
                JugadorDAO jugadorDAO = new JugadorDAO();
                id = jugadorDAO.actualizarJugador(jugador1, this.idJugador);
               
                
                if (id != 0){
                JOptionPane.showMessageDialog(null, "Se ha actualizado el jugador (" + nombre + ") exitosmente.", "Canchas Gonzalez", JOptionPane.INFORMATION_MESSAGE);
                
                VistaJugadores vistaJugadores = new VistaJugadores();
                vistaJugadores.setVisible(true);
                dispose();
                }
                else {
                    JOptionPane.showMessageDialog(null, "No se pudo actualizar el jugador (" + nombre + ") vuelve a intentar.", "Canchas Gonzalez", JOptionPane.INFORMATION_MESSAGE);
                }
                
            } catch (SQLException ex) {
                Logger.getLogger(VistaJugadoresActualizar.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, "No se pudo actualizar el jugador (" + nombre + ") vuelve a intentar.", "Canchas Gonzalez", JOptionPane.INFORMATION_MESSAGE);
            }
            
            
            
            
            
           //label.setText("You selected: Yes");
        }else if (result == JOptionPane.NO_OPTION){
            System.out.println(2);
           //label.setText("You selected: No");
        }else {
            System.out.println(3);
        }
        
    }//GEN-LAST:event_btnActualizarJugadorActionPerformed

    private void txtfNumeroCamisetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfNumeroCamisetaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfNumeroCamisetaActionPerformed

    private void txtfFechaNacimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfFechaNacimientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfFechaNacimientoActionPerformed

    private void txtfIdEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfIdEquipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfIdEquipoActionPerformed

    private void btnRegresar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresar2ActionPerformed

        VistaJugadores vistaJugadores = new VistaJugadores();
        vistaJugadores.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnRegresar2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaJugadoresActualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaJugadoresActualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaJugadoresActualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaJugadoresActualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaJugadoresActualizar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarJugador;
    private javax.swing.JButton btnRegresar2;
    private javax.swing.JLabel lblApellidoMaterno1;
    private javax.swing.JLabel lblApellidoPaterno1;
    private javax.swing.JLabel lblAside;
    private javax.swing.JLabel lblFechaNacimiento;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblIcono;
    private javax.swing.JLabel lblIdArbitro1;
    private javax.swing.JLabel lblIdEquipo;
    private javax.swing.JLabel lblLogoEmpresa;
    private javax.swing.JLabel lblNombres1;
    private javax.swing.JLabel lblNumeroCamiseta;
    private javax.swing.JLabel lblPosicion;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtfApellidoMaterno;
    private javax.swing.JTextField txtfApellidoPaterno;
    private javax.swing.JTextField txtfFechaNacimiento;
    private javax.swing.JTextField txtfIdEquipo;
    private javax.swing.JTextField txtfIdJugador;
    private javax.swing.JTextField txtfNombres;
    private javax.swing.JTextField txtfNumeroCamiseta;
    private javax.swing.JTextField txtfPosicion;
    // End of variables declaration//GEN-END:variables
}
