/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frontEnd;

import backEnd.Utilidades;

/**
 *
 * @author josue
 */
public class VistaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VistaPlantilla
     */
    public VistaPrincipal() {
        initComponents();
        Utilidades.cargarLogo(this, "LOGOEMPRESA.png");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCanchas = new javax.swing.JButton();
        btnArbitros = new javax.swing.JButton();
        btnEquipos = new javax.swing.JButton();
        btnJugadores = new javax.swing.JButton();
        lblLogo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1280, 720));
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setPreferredSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(null);

        btnCanchas.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btnCanchas.setText("CANCHAS");
        btnCanchas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCanchasActionPerformed(evt);
            }
        });
        getContentPane().add(btnCanchas);
        btnCanchas.setBounds(70, 100, 320, 110);

        btnArbitros.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btnArbitros.setText("ARBITROS");
        btnArbitros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArbitrosActionPerformed(evt);
            }
        });
        getContentPane().add(btnArbitros);
        btnArbitros.setBounds(70, 500, 320, 110);

        btnEquipos.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btnEquipos.setText("EQUIPOS");
        btnEquipos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEquiposActionPerformed(evt);
            }
        });
        getContentPane().add(btnEquipos);
        btnEquipos.setBounds(890, 90, 320, 110);

        btnJugadores.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btnJugadores.setText("JUGADORES");
        btnJugadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJugadoresActionPerformed(evt);
            }
        });
        getContentPane().add(btnJugadores);
        btnJugadores.setBounds(890, 490, 320, 110);

        lblLogo.setIcon(new javax.swing.ImageIcon("C:\\Imagenes\\LOGOEMPRESA.png")); // NOI18N
        getContentPane().add(lblLogo);
        lblLogo.setBounds(520, 160, 200, 210);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setText("CANCHAS GONZÁLEZ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(390, 330, 510, 140);

        lblFondo.setIcon(new javax.swing.ImageIcon("C:\\Imagenes\\FONDOC.jpg")); // NOI18N
        getContentPane().add(lblFondo);
        lblFondo.setBounds(0, -30, 1370, 780);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCanchasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCanchasActionPerformed
        VistaReservarCancha vistaReservarCancha = new VistaReservarCancha(Utilidades.fechaHoy());
        vistaReservarCancha.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnCanchasActionPerformed

    private void btnArbitrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArbitrosActionPerformed
        // TODO add your handling code here:
        VistaArbitros vistaArbitro = new VistaArbitros();
        vistaArbitro.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnArbitrosActionPerformed

    private void btnJugadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJugadoresActionPerformed
        // TODO add your handling code here:
        VistaJugadores vistaJugadores = new VistaJugadores();
        vistaJugadores.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnJugadoresActionPerformed

    private void btnEquiposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEquiposActionPerformed
        // TODO add your handling code here:
        VistaEquipos vistaEquipos = new VistaEquipos();
        vistaEquipos.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnEquiposActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnArbitros;
    private javax.swing.JButton btnCanchas;
    private javax.swing.JButton btnEquipos;
    private javax.swing.JButton btnJugadores;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblLogo;
    // End of variables declaration//GEN-END:variables
}
