/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frontEnd;
import backEnd.Utilidades;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author josue
 */
public class VistaJugadoresVerPorId extends javax.swing.JFrame {

    /**
     * Creates new form VistaPlantilla
     */
    public VistaJugadoresVerPorId() {
        initComponents();
        Utilidades.cargarLogo(this, "LOGOEMPRESA.png");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblIdArbitro1 = new javax.swing.JLabel();
        lblNombres1 = new javax.swing.JLabel();
        lblApellidoPaterno1 = new javax.swing.JLabel();
        lblApellidoMaterno1 = new javax.swing.JLabel();
        lblNumeroCamiseta = new javax.swing.JLabel();
        lblPosicion = new javax.swing.JLabel();
        lblFechaNacimiento = new javax.swing.JLabel();
        lblIdEquipo = new javax.swing.JLabel();
        txtfIdJugador = new javax.swing.JTextField();
        txtfNombres = new javax.swing.JTextField();
        txtfApellidoPaterno = new javax.swing.JTextField();
        txtfApellidoMaterno = new javax.swing.JTextField();
        txtfNumeroCamiseta = new javax.swing.JTextField();
        txtfPosicion = new javax.swing.JTextField();
        txtfFechaNacimiento = new javax.swing.JTextField();
        txtfIdEquipo = new javax.swing.JTextField();
        lblLogoEmpresa = new javax.swing.JLabel();
        btnRegresar2 = new javax.swing.JButton();
        lblTitulo = new javax.swing.JLabel();
        lblIcono = new javax.swing.JLabel();
        lblFondo = new javax.swing.JLabel();
        lblAside = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CREAR ARBITRO");
        setMinimumSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(null);

        lblIdArbitro1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblIdArbitro1.setText("ID JUGADOR");
        getContentPane().add(lblIdArbitro1);
        lblIdArbitro1.setBounds(340, 50, 190, 40);

        lblNombres1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblNombres1.setText("NOMBRES");
        getContentPane().add(lblNombres1);
        lblNombres1.setBounds(340, 120, 190, 40);

        lblApellidoPaterno1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblApellidoPaterno1.setText("APELLIDO  PATERNO");
        getContentPane().add(lblApellidoPaterno1);
        lblApellidoPaterno1.setBounds(340, 180, 250, 40);

        lblApellidoMaterno1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblApellidoMaterno1.setText("APELLIDO  MATERNO");
        getContentPane().add(lblApellidoMaterno1);
        lblApellidoMaterno1.setBounds(340, 250, 250, 40);

        lblNumeroCamiseta.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblNumeroCamiseta.setText("NUMERO CAMISETA");
        getContentPane().add(lblNumeroCamiseta);
        lblNumeroCamiseta.setBounds(340, 320, 250, 40);

        lblPosicion.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblPosicion.setText("POSICION");
        getContentPane().add(lblPosicion);
        lblPosicion.setBounds(340, 390, 250, 40);

        lblFechaNacimiento.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblFechaNacimiento.setText("FECHA NACIMIENTO");
        getContentPane().add(lblFechaNacimiento);
        lblFechaNacimiento.setBounds(340, 450, 250, 40);

        lblIdEquipo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblIdEquipo.setText("ID EQUIPO");
        getContentPane().add(lblIdEquipo);
        lblIdEquipo.setBounds(340, 510, 250, 40);

        txtfIdJugador.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtfIdJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfIdJugadorActionPerformed(evt);
            }
        });
        getContentPane().add(txtfIdJugador);
        txtfIdJugador.setBounds(660, 50, 330, 40);

        txtfNombres.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtfNombres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfNombresActionPerformed(evt);
            }
        });
        getContentPane().add(txtfNombres);
        txtfNombres.setBounds(660, 110, 330, 40);

        txtfApellidoPaterno.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtfApellidoPaterno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfApellidoPaternoActionPerformed(evt);
            }
        });
        getContentPane().add(txtfApellidoPaterno);
        txtfApellidoPaterno.setBounds(660, 180, 330, 40);

        txtfApellidoMaterno.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtfApellidoMaterno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfApellidoMaternoActionPerformed(evt);
            }
        });
        getContentPane().add(txtfApellidoMaterno);
        txtfApellidoMaterno.setBounds(660, 250, 330, 40);

        txtfNumeroCamiseta.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtfNumeroCamiseta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfNumeroCamisetaActionPerformed(evt);
            }
        });
        getContentPane().add(txtfNumeroCamiseta);
        txtfNumeroCamiseta.setBounds(660, 320, 330, 40);

        txtfPosicion.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtfPosicion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfPosicionActionPerformed(evt);
            }
        });
        getContentPane().add(txtfPosicion);
        txtfPosicion.setBounds(660, 390, 330, 40);

        txtfFechaNacimiento.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtfFechaNacimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfFechaNacimientoActionPerformed(evt);
            }
        });
        getContentPane().add(txtfFechaNacimiento);
        txtfFechaNacimiento.setBounds(660, 450, 330, 40);

        txtfIdEquipo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtfIdEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfIdEquipoActionPerformed(evt);
            }
        });
        getContentPane().add(txtfIdEquipo);
        txtfIdEquipo.setBounds(660, 510, 330, 40);

        lblLogoEmpresa.setIcon(new javax.swing.ImageIcon("C:\\Imagenes\\LOGOEMPRESA.png")); // NOI18N
        getContentPane().add(lblLogoEmpresa);
        lblLogoEmpresa.setBounds(20, 80, 180, 190);

        btnRegresar2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnRegresar2.setText("REGRESAR");
        btnRegresar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresar2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegresar2);
        btnRegresar2.setBounds(30, 600, 190, 70);

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("JUGADOR");
        getContentPane().add(lblTitulo);
        lblTitulo.setBounds(0, 320, 250, 80);

        lblIcono.setIcon(new javax.swing.ImageIcon("C:\\Imagenes\\jugadores.png")); // NOI18N
        getContentPane().add(lblIcono);
        lblIcono.setBounds(1000, 170, 340, 380);

        lblFondo.setIcon(new javax.swing.ImageIcon("C:\\Imagenes\\fondo1.png")); // NOI18N
        getContentPane().add(lblFondo);
        lblFondo.setBounds(250, 0, 1030, 720);

        lblAside.setIcon(new javax.swing.ImageIcon("C:\\Imagenes\\FONDOC.jpg")); // NOI18N
        getContentPane().add(lblAside);
        lblAside.setBounds(0, 0, 1290, 730);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtfIdJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfIdJugadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfIdJugadorActionPerformed

    private void txtfNombresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfNombresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfNombresActionPerformed

    private void txtfApellidoPaternoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfApellidoPaternoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfApellidoPaternoActionPerformed

    private void txtfApellidoMaternoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfApellidoMaternoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfApellidoMaternoActionPerformed

    private void txtfNumeroCamisetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfNumeroCamisetaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfNumeroCamisetaActionPerformed

    private void txtfPosicionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfPosicionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfPosicionActionPerformed

    private void txtfFechaNacimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfFechaNacimientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfFechaNacimientoActionPerformed

    private void txtfIdEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfIdEquipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfIdEquipoActionPerformed

    private void btnRegresar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresar2ActionPerformed
        VistaJugadores vistaJugadores = new VistaJugadores();
        vistaJugadores.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnRegresar2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaJugadoresVerPorId.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaJugadoresVerPorId.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaJugadoresVerPorId.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaJugadoresVerPorId.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaJugadoresVerPorId().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegresar2;
    private javax.swing.JLabel lblApellidoMaterno1;
    private javax.swing.JLabel lblApellidoPaterno1;
    private javax.swing.JLabel lblAside;
    private javax.swing.JLabel lblFechaNacimiento;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblIcono;
    private javax.swing.JLabel lblIdArbitro1;
    private javax.swing.JLabel lblIdEquipo;
    private javax.swing.JLabel lblLogoEmpresa;
    private javax.swing.JLabel lblNombres1;
    private javax.swing.JLabel lblNumeroCamiseta;
    private javax.swing.JLabel lblPosicion;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtfApellidoMaterno;
    private javax.swing.JTextField txtfApellidoPaterno;
    private javax.swing.JTextField txtfFechaNacimiento;
    private javax.swing.JTextField txtfIdEquipo;
    private javax.swing.JTextField txtfIdJugador;
    private javax.swing.JTextField txtfNombres;
    private javax.swing.JTextField txtfNumeroCamiseta;
    private javax.swing.JTextField txtfPosicion;
    // End of variables declaration//GEN-END:variables
}
