/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frontEnd;

import backEnd.Arbitro;
import backEnd.ArbitroDAO;
import backEnd.Utilidades;
import java.sql.SQLException;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author josue
 */
public class VistaArbitros extends javax.swing.JFrame {

    /**
     * Creates new form VistaPlantilla
     */
    public VistaArbitros() {
        initComponents();
        
        Utilidades.cargarLogo(this, "LOGOEMPRESA.png");
        
        
        DefaultTableModel model = (DefaultTableModel) tblArbitros.getModel();


        ArbitroDAO arbitroDAO = new ArbitroDAO();

        // Obtener todos los productos
        List<Arbitro> todosArbitros = arbitroDAO.obtenerArbitros();
        System.out.println("Todos los Arbitros:");
        for (Arbitro arbitro : todosArbitros) {

            model.addRow(new Object[]{
                arbitro.getIdArbitro(),
                arbitro.getNombre(),
                arbitro.getApellidoPaterno(),
                arbitro.getApellidoMaterno(),
                arbitro.getTelefono(),
                (arbitro.isDisponible() != 0)
            });
        }

    
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblArbitros = new javax.swing.JTable();
        btnVisualizar = new javax.swing.JButton();
        btnCrear1 = new javax.swing.JButton();
        btnActualizar1 = new javax.swing.JButton();
        btnEliminar1 = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(null);

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        lblTitulo.setText("ARBITROS");
        getContentPane().add(lblTitulo);
        lblTitulo.setBounds(490, 10, 470, 60);

        tblArbitros.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblArbitros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID ARBITRO", "NOMBRE", "APELLIDO PATERNO", "APELLIDO MATERNO", "TELEFONO", "DISPONIBLE"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblArbitros.setColumnSelectionAllowed(true);
        tblArbitros.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(tblArbitros);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(70, 110, 750, 410);

        btnVisualizar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnVisualizar.setText("VISUALIZAR");
        btnVisualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisualizarActionPerformed(evt);
            }
        });
        getContentPane().add(btnVisualizar);
        btnVisualizar.setBounds(890, 320, 230, 40);

        btnCrear1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnCrear1.setText("CREAR");
        btnCrear1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrear1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnCrear1);
        btnCrear1.setBounds(890, 230, 220, 40);

        btnActualizar1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnActualizar1.setText("ACTUALIZAR");
        btnActualizar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizar1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnActualizar1);
        btnActualizar1.setBounds(890, 400, 230, 40);

        btnEliminar1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnEliminar1.setText("ELIMINAR");
        btnEliminar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminar1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminar1);
        btnEliminar1.setBounds(890, 470, 230, 40);

        btnRegresar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnRegresar.setText("REGRESAR");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegresar);
        btnRegresar.setBounds(40, 630, 190, 70);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrear1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrear1ActionPerformed
        // TODO add your handling code here:
        VistaArbitrosCrear vistaArbitrosCrear = new VistaArbitrosCrear();
        vistaArbitrosCrear.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnCrear1ActionPerformed

    private void btnVisualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisualizarActionPerformed
        int selectedRow = tblArbitros.getSelectedRow();

        if(selectedRow != -1){
            int idArbitro = (int) tblArbitros.getValueAt(selectedRow, 0);
            System.out.println(idArbitro);

            VistaArbitrosVerPorId vistaArbitrosVerPorId  = new VistaArbitrosVerPorId(idArbitro);
            vistaArbitrosVerPorId.setVisible(true);
            dispose();
        }else{
             JOptionPane.showMessageDialog(null, "Por favor selecciona un arbitro");
        }
        
        
    }//GEN-LAST:event_btnVisualizarActionPerformed

    private void btnActualizar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizar1ActionPerformed
        
        int selectedRow = tblArbitros.getSelectedRow();

        if(selectedRow != -1){
            int idArbitro = (int) tblArbitros.getValueAt(selectedRow, 0);
            System.out.println(idArbitro);

            VistaArbitrosActualizar vistaArbitrosActualizar  = new VistaArbitrosActualizar(idArbitro);
            vistaArbitrosActualizar.setVisible(true);
            dispose();
        }else{
             JOptionPane.showMessageDialog(null, "Por favor selecciona un arbitro");
        }
        
        
    }//GEN-LAST:event_btnActualizar1ActionPerformed

    private void btnEliminar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminar1ActionPerformed
        
        
        int selectedRow = tblArbitros.getSelectedRow();

        if(selectedRow != -1){
            int idArbitro = (int) tblArbitros.getValueAt(selectedRow, 0);
            System.out.println(idArbitro);
            
            //CONFIRMACION PARA ELIMINAR
        
         int result = JOptionPane.showConfirmDialog(
                new JFrame(),
                "¿ESTAS SEGURO DE ELIMINAR ESTE REGISTRO?", 
                "CANCHASGONZALEZ - CONFIRMACION",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE
            );

            if(result == JOptionPane.YES_OPTION){
                System.out.println(1);
                

                ArbitroDAO arbitroDAO = new ArbitroDAO();
                int id = arbitroDAO.eliminarArbitro(idArbitro);
                
                if (id != 0){
                   JOptionPane.showMessageDialog(null, "Se ha eliminado el arbitro  exitosamente.", "Canchas Gonzalez", JOptionPane.INFORMATION_MESSAGE);

                    VistaArbitros vistaArbitros = new VistaArbitros();
                    vistaArbitros.setVisible(true);
                    dispose();
                }
                else {
                    JOptionPane.showMessageDialog(null, "No se pudo eliminar el arbitro, vuelve a intentar.", "Canchas Gonzalez", JOptionPane.INFORMATION_MESSAGE);
                }

                
               //label.setText("You selected: Yes");
            }else if (result == JOptionPane.NO_OPTION){
                System.out.println(2);
               //label.setText("You selected: No");
            }else {
                System.out.println(3);
            }

        }else{
             JOptionPane.showMessageDialog(null, "Por favor selecciona un arbitro");
        }
        
    
    }//GEN-LAST:event_btnEliminar1ActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
        VistaPrincipal vistaPrincipal = new VistaPrincipal();
        vistaPrincipal.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaArbitros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaArbitros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaArbitros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaArbitros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaArbitros().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar1;
    private javax.swing.JButton btnCrear1;
    private javax.swing.JButton btnEliminar1;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton btnVisualizar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTable tblArbitros;
    // End of variables declaration//GEN-END:variables
}
