/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frontEnd;
import backEnd.Arbitro;
import backEnd.ArbitroDAO;
import backEnd.Equipo;
import backEnd.EquipoDAO;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author josue
 */
public class VistaEquiposActualizar extends javax.swing.JFrame {

    //ATRIBUTOS
    private int idEquipo;

    public int getIdEquipo() {
        return idEquipo;
    }

    public void setIdEquipo(int idEquipo) {
        this.idEquipo = idEquipo;
    }
    
    
    public VistaEquiposActualizar() {
        initComponents();
    }
    
    
     public VistaEquiposActualizar(int idEquipo) {
        initComponents();
        
        this.idEquipo = idEquipo;
        
        EquipoDAO equipoDAO = new EquipoDAO();
        try {
            Equipo equipo = equipoDAO.obtenerEquipoPorId(idEquipo);
            txtfIdEquipo.setText(String.valueOf(equipo.getIdEquipo()));
            txtfNombre.setText(equipo.getNombre());
            txtfTelefono.setText(equipo.getTelefono());
        } catch (SQLException ex) {
            Logger.getLogger(VistaEquiposActualizar.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLogoEmpresa = new javax.swing.JLabel();
        btnActualizarEquipo = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        lblNombre = new javax.swing.JLabel();
        lbLTelefono = new javax.swing.JLabel();
        lblIdEquipo = new javax.swing.JLabel();
        txtfNombre = new javax.swing.JTextField();
        txtfTelefono = new javax.swing.JTextField();
        txtfIdEquipo = new javax.swing.JTextField();
        lblTitulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CREAR ARBITRO");
        setMinimumSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(null);

        lblLogoEmpresa.setIcon(new javax.swing.ImageIcon("C:\\Imagenes\\LOGOEMPRESA.png")); // NOI18N
        getContentPane().add(lblLogoEmpresa);
        lblLogoEmpresa.setBounds(-40, 0, 180, 190);

        btnActualizarEquipo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnActualizarEquipo.setText("ACTUALIZAR EQUIPO");
        btnActualizarEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarEquipoActionPerformed(evt);
            }
        });
        getContentPane().add(btnActualizarEquipo);
        btnActualizarEquipo.setBounds(960, 600, 290, 70);

        btnRegresar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnRegresar.setText("REGRESAR");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegresar);
        btnRegresar.setBounds(30, 630, 190, 70);

        lblNombre.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        lblNombre.setText("NOMBRE");
        getContentPane().add(lblNombre);
        lblNombre.setBounds(430, 290, 250, 40);

        lbLTelefono.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        lbLTelefono.setText("TELEFONO");
        getContentPane().add(lbLTelefono);
        lbLTelefono.setBounds(430, 450, 310, 40);

        lblIdEquipo.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        lblIdEquipo.setText("ID EQUIPO");
        getContentPane().add(lblIdEquipo);
        lblIdEquipo.setBounds(420, 140, 310, 60);

        txtfNombre.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        txtfNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfNombreActionPerformed(evt);
            }
        });
        getContentPane().add(txtfNombre);
        txtfNombre.setBounds(340, 360, 400, 60);

        txtfTelefono.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        txtfTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfTelefonoActionPerformed(evt);
            }
        });
        getContentPane().add(txtfTelefono);
        txtfTelefono.setBounds(340, 530, 400, 60);

        txtfIdEquipo.setEditable(false);
        txtfIdEquipo.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        txtfIdEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfIdEquipoActionPerformed(evt);
            }
        });
        getContentPane().add(txtfIdEquipo);
        txtfIdEquipo.setBounds(340, 210, 400, 60);

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        lblTitulo.setText("EQUIPOS");
        getContentPane().add(lblTitulo);
        lblTitulo.setBounds(450, 0, 440, 80);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnActualizarEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarEquipoActionPerformed
        
        String nombre = txtfNombre.getText();
        System.out.println(nombre);
        
        String telefono = txtfTelefono.getText();
        System.out.println(telefono);
        
    
        //CONFIRMACION DE CREAR
        int result = JOptionPane.showConfirmDialog(
                new JFrame(),
                "¿ESTAS SEGURO DE ACTUALIZARLO?", 
                "CANCHASGONZALEZ - CONFIRMACION",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE
            );

        if(result == JOptionPane.YES_OPTION){
            System.out.println(1);
            Equipo equipo1 = new Equipo(nombre, telefono);
            System.out.println(equipo1);
            
            EquipoDAO equipoDAO = new EquipoDAO();
            
           
            int id;
            try {
                id = equipoDAO.actualizarEquipo(equipo1, this.idEquipo);
                
                if (id != 0){
                JOptionPane.showMessageDialog(null, "Se ha actualizado el equipo (" + nombre + ") exitosmente.", "Canchas Gonzalez", JOptionPane.INFORMATION_MESSAGE);
                
                VistaEquipos vistaEquipos = new VistaEquipos();
                vistaEquipos.setVisible(true);
                dispose();
                }
                else {
                    JOptionPane.showMessageDialog(null, "No se pudo actualizar el equipo (" + nombre + ") vuelve a intentar.", "Canchas Gonzalez", JOptionPane.INFORMATION_MESSAGE);
                }
                
            } catch (SQLException ex) {
                Logger.getLogger(VistaEquiposActualizar.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, "No se pudo actualizar el equipo (" + nombre + ") vuelve a intentar.", "Canchas Gonzalez", JOptionPane.INFORMATION_MESSAGE);
            }
            
            
            
            
            
           //label.setText("You selected: Yes");
        }else if (result == JOptionPane.NO_OPTION){
            System.out.println(2);
           //label.setText("You selected: No");
        }else {
            System.out.println(3);
        }
        
    }//GEN-LAST:event_btnActualizarEquipoActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
     VistaEquipos vistaEquipos = new VistaEquipos();
     vistaEquipos.setVisible(true);
     dispose();
            
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void txtfNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfNombreActionPerformed

    private void txtfTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfTelefonoActionPerformed

    private void txtfIdEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfIdEquipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfIdEquipoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaEquiposActualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaEquiposActualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaEquiposActualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaEquiposActualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaEquiposActualizar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarEquipo;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel lbLTelefono;
    private javax.swing.JLabel lblIdEquipo;
    private javax.swing.JLabel lblLogoEmpresa;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtfIdEquipo;
    private javax.swing.JTextField txtfNombre;
    private javax.swing.JTextField txtfTelefono;
    // End of variables declaration//GEN-END:variables
}
