/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frontEnd;

import backEnd.Arbitro;
import backEnd.ArbitroDAO;
import backEnd.EquipoDAO;
import backEnd.Jugador;
import backEnd.JugadorDAO;
import backEnd.Utilidades;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author josue
 */
public class VistaJugadores extends javax.swing.JFrame {

    /**
     * Creates new form VistaPlantilla
     */
    public VistaJugadores() {
        initComponents();
        Utilidades.cargarLogo(this, "LOGOEMPRESA.png");
        
        DefaultTableModel model = (DefaultTableModel) tblJugadores.getModel();

        try {
            JugadorDAO jugadorDAO = new JugadorDAO();
            
            // Obtener todos los productos
            List<Jugador> jugadores = jugadorDAO.obtenerJugadores();
            System.out.println("Todos los Jugadores:");
            for (Jugador jugador : jugadores) {

                model.addRow(new Object[]{
                    jugador.getIdJugador(),
                    jugador.getNombre(),
                    jugador.getApellidoPaterno(),
                    jugador.getApellidoMaterno(),
                    jugador.getNumeroCamiseta(),
                    jugador.getPosicion(),
                    jugador.getFechaNacimiento(),
                    jugador.getIdEquipo()
                });
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(VistaJugadores.class.getName()).log(Level.SEVERE, null, ex);
        }
        

        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblJugadores = new javax.swing.JTable();
        btnVisualizar = new javax.swing.JButton();
        btnCrear1 = new javax.swing.JButton();
        btnActualizar1 = new javax.swing.JButton();
        btnEliminar1 = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        lblIcono = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();
        lblTitulo1 = new javax.swing.JLabel();
        lblFondo = new javax.swing.JLabel();
        lblAside = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(null);

        tblJugadores.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblJugadores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID JUGADOR", "NOMBRE", "APELLIDO PATERNO", "APELLIDO MATERNO", "NUMERO CAMISETA", "POSICION", "FECHA NACIMINETO", "ID EQUIPO"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblJugadores);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(30, 100, 950, 510);

        btnVisualizar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnVisualizar.setText("VISUALIZAR");
        btnVisualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisualizarActionPerformed(evt);
            }
        });
        getContentPane().add(btnVisualizar);
        btnVisualizar.setBounds(1040, 230, 210, 40);

        btnCrear1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnCrear1.setText("CREAR");
        btnCrear1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrear1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnCrear1);
        btnCrear1.setBounds(1040, 180, 210, 40);

        btnActualizar1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnActualizar1.setText("ACTUALIZAR");
        btnActualizar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizar1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnActualizar1);
        btnActualizar1.setBounds(1040, 280, 210, 40);

        btnEliminar1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnEliminar1.setText("ELIMINAR");
        btnEliminar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminar1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminar1);
        btnEliminar1.setBounds(1040, 330, 210, 40);

        btnRegresar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnRegresar.setText("REGRESAR");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegresar);
        btnRegresar.setBounds(40, 630, 190, 70);

        lblIcono.setIcon(new javax.swing.ImageIcon("C:\\Imagenes\\jugadores.png")); // NOI18N
        getContentPane().add(lblIcono);
        lblIcono.setBounds(1010, 360, 340, 380);

        lblLogo.setIcon(new javax.swing.ImageIcon("C:\\Imagenes\\LOGOEMPRESA.png")); // NOI18N
        getContentPane().add(lblLogo);
        lblLogo.setBounds(1040, 0, 230, 170);

        lblTitulo1.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        lblTitulo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo1.setText("JUGADORES");
        getContentPane().add(lblTitulo1);
        lblTitulo1.setBounds(70, 20, 910, 60);

        lblFondo.setIcon(new javax.swing.ImageIcon("C:\\Imagenes\\fondo1.png")); // NOI18N
        getContentPane().add(lblFondo);
        lblFondo.setBounds(0, 0, 1010, 730);

        lblAside.setIcon(new javax.swing.ImageIcon("C:\\Imagenes\\FONDOC.jpg")); // NOI18N
        getContentPane().add(lblAside);
        lblAside.setBounds(880, 0, 400, 730);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrear1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrear1ActionPerformed
        // TODO add your handling code here:
        VistaJugadoresCrear vistaJugadoresCrear = new VistaJugadoresCrear();
        vistaJugadoresCrear.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnCrear1ActionPerformed

    private void btnVisualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisualizarActionPerformed
        
        int selectedRow = tblJugadores.getSelectedRow();

        if(selectedRow != -1){
            int idJugador = (int) tblJugadores.getValueAt(selectedRow, 0);
            System.out.println(idJugador);

            VistaJugadoresVerPorId vistaJugadoresVerPorId  = new VistaJugadoresVerPorId(idJugador);
            vistaJugadoresVerPorId.setVisible(true);
            dispose();
        }else{
             JOptionPane.showMessageDialog(null, "Por favor selecciona un equipo");
        }
        
         
    }//GEN-LAST:event_btnVisualizarActionPerformed

    private void btnActualizar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizar1ActionPerformed
      
        int selectedRow = tblJugadores.getSelectedRow();

        if(selectedRow != -1){
            int idJugador = (int) tblJugadores.getValueAt(selectedRow, 0);
            System.out.println(idJugador);

            VistaJugadoresActualizar vistaJugadoresActualizar  = new VistaJugadoresActualizar(idJugador);
            vistaJugadoresActualizar.setVisible(true);
            dispose();
        }else{
             JOptionPane.showMessageDialog(null, "Por favor selecciona un equipo");
        }
        
        
    }//GEN-LAST:event_btnActualizar1ActionPerformed

    private void btnEliminar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminar1ActionPerformed
        
         int selectedRow = tblJugadores.getSelectedRow();

        if(selectedRow != -1){
            int idJugador = (int) tblJugadores.getValueAt(selectedRow, 0);
            System.out.println(idJugador);
            
            //CONFIRMACION PARA ELIMINAR
        
         int result = JOptionPane.showConfirmDialog(
                new JFrame(),
                "¿ESTAS SEGURO DE ELIMINAR ESTE REGISTRO?", 
                "CANCHASGONZALEZ - CONFIRMACION",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE
            );

            if(result == JOptionPane.YES_OPTION){
                System.out.println(1);
                
                
                int id;
                try {
                    JugadorDAO jugadorDAO = new JugadorDAO();
                    id = jugadorDAO.eliminarJugador(idJugador);
                    
                    if (id != 0){
                   JOptionPane.showMessageDialog(null, "Se ha eliminado el  jugador exitosamente.", "Canchas Gonzalez", JOptionPane.INFORMATION_MESSAGE);
                   
                   
                    VistaJugadores vistaJugadores = new VistaJugadores();
                    vistaJugadores.setVisible(true);
                    dispose();
                    }
                    else {
                        JOptionPane.showMessageDialog(null, "No se pudo eliminar el jugador, vuelve a intentar.", "Canchas Gonzalez", JOptionPane.INFORMATION_MESSAGE);
                    }
                    
                } catch (SQLException ex) {
                    Logger.getLogger(VistaJugadores.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(null, "No se pudo eliminar el jugador, vuelve a intentar.", "Canchas Gonzalez", JOptionPane.INFORMATION_MESSAGE);
                }
                
                
                

                
               //label.setText("You selected: Yes");
            }else if (result == JOptionPane.NO_OPTION){
                System.out.println(2);
               //label.setText("You selected: No");
            }else {
                System.out.println(3);
            }

        }else{
             JOptionPane.showMessageDialog(null, "Por favor selecciona un arbitro");
        }
    }//GEN-LAST:event_btnEliminar1ActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
        VistaPrincipal vistaPrincipal = new VistaPrincipal();
        vistaPrincipal.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaJugadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaJugadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaJugadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaJugadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaJugadores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar1;
    private javax.swing.JButton btnCrear1;
    private javax.swing.JButton btnEliminar1;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton btnVisualizar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAside;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblIcono;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblTitulo1;
    private javax.swing.JTable tblJugadores;
    // End of variables declaration//GEN-END:variables
}
